### ISSUE TITLE
Latest version not working in our CI environment

### ISSUE THREAD

**Issue by steveryan** [Azure/azure-cosmos-db-emulator-docker#111]
**Describe the bug**
Our CI has pulled the `:latest` image for the last ~18 months, and things have worked fine up to and including `sha256:bf9ddf53430701e6d954bdc8cd07ef672f0642a55244e2d4b0b478a633e89d27`. 

Images after that have left our CI waiting at `Waiting on explorer at https://localhost:8081/_explorer/index.html` indefinitely (45+ minutes). 

**Expected behavior**
The `:latest` image should function the same as previous versions.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Docker Images Used: **
 - Linux

**Comment by niteshvijay1995** [comment]
@steveryan  Can you please share the docker logs from your CI pipeline. 
Also share the cmd used to start docker container.

**Comment by steveryan** [comment]
Let me get you the logs, but while I dig into that, we are starting the container with the following

`docker-compose up -d --remove-orphans cosmosdb`

and that docker compose bit is as follows
```
version: "3.8"

services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmos
    tty: true
    cpu_count: 2
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - "8081:8081"
      - "8900:8900"
      - "8901:8901"
      - "8979:8979"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    networks:
      - default
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "10.1.11.0/24"

```
