### ISSUE TITLE
_explorer/emulator.pem can't provide a secure connection

### ISSUE THREAD

**Issue by pmottmwi** [Azure/azure-cosmos-db-emulator-docker#117]
**Describe the bug**
Using the cosmosEmulatorVnextPreview linux container image, calling _explorer/emulator.pem returns an error.

**To Reproduce**
1. Start Cosmos emulator docker container.
2. Navigate to https://localhost:8081/_explorer/emulator.pem.
3. See error: "This site can't provide a secure connection. localhost sent an invalid response. ERR_SLL_PROTOCOL_ERROR.".

**Expected behavior**
Response should contain the certificate to use for SSL connections to the Cosmos instance.

**Desktop (please complete the following information):**
 - OS: Mac OS 14.6.1
 - Browser: Chrome
 - Version: 131.0.6778.70

**Docker Images Used:**
 - Linux (cosmosEmulatorVnextPreview)
 
**Docker Environment**
- Docker Desktop 4.35.1
 - Docker compose:
```yaml
name: Cosmos Emulator
services:
    azure-cosmos-emulator:
        ports:
            - 8081:8081
            - 1234:1234
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        command: --protocol https
```
