### ISSUE TITLE
Linux Azure Emulator does not work in Direct mode with .NET SDK

### ISSUE THREAD

**Issue by mrnustik** [Azure/azure-cosmos-db-emulator-docker#161]
Hi,

**Describe the bug**
I was trying to use the Azure Emulator locally with our integration tests suite. We use Direct mode connection within out app and I wanted to keep that in the Integration tests as well.

Unfortunately when running the Azure Emulator locally the Cosmos SDK throws exception when connecting to emulator in Direct mode. The same code described bellow runs well against the full Cosmos in Azure.

**To Reproduce**
1. Run the container
2. Create new .NET project
3. Install Microsoft.Azure.Cosmos NuGet pcakage 
4. Run the following code
```
var cosmosClientOptions = new CosmosClientOptions
{
    ConnectionMode = ConnectionMode.Direct,
    HttpClientFactory = () => _container.HttpClient,
};

var cosmosClient = new CosmosClient(
"AccountEndpoint=https://127.0.0.1:8081;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
    cosmosClientOptions);
await cosmosClient.CreateDatabaseIfNotExistsAsync("Test");
```
5. See the following exception
```
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 6a54839f-c8e7-44d1-8b8b-703cd29d8832; Reason: ({"code":"BadRequest","message":"Request url is invalid.\r\nActivityId: 42d85f45-5455-452a-913c-674962bea87f, Microsoft.Azure.Documents.Common/2.14.0"}
RequestUri: https://127.0.0.1:8081//addresses/%3F$resolveFor=dbs&$filter=protocol eq rntbd;
RequestMethod: GET;
Header: Authorization Length: 84;
Header: x-ms-date Length: 29;
Header: Cache-Control Length: 8;
Header: User-Agent Length: 90;
Header: x-ms-version Length: 10;
Header: x-ms-cosmos-sdk-supportedcapabilities Length: 1;
Header: Accept Length: 16;
, Request URI: //addresses/%3F$resolveFor=dbs&$filter=protocol%20eq%20rntbd, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22631 cosmos-netstandard-sdk/3.35.0);
```

**Desktop (please complete the following information):**
 - OS: Windows 11

**Docker Images Used: **
 - Linux

**Arguments && Environment variables to start Docker:
 
**Docker Environment**
 - Docker compose
```
services:
  cosmosdb:
     image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
     ports:
       - 8081:8081
       - 10250:10250
       - 10251:10251
       - 10252:10252
       - 10253:10253
       - 10254:10254
       - 10255:10255
     environment:
       - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=80
       - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false
       - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
```
 
**Additional context**
