### ISSUE TITLE
Unable to connect from an application running as docker container to cosmos next-review emulator

### ISSUE THREAD

**Issue by sramanan0425** [Azure/azure-cosmos-db-emulator-docker#166]
**Describe the bug**
I am trying to use the cosmos emulator vnext-preview (docker.repo1.uhc.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview) for local development and testing from a spring boot application. I am using azure-cosmos sdk 4.66.1. My application is able to successfully connect using either http or https if I run this as a java application. For https, I have the emulator certs imported into my cacerts for the jdk as described [here](https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-linux). 

My issue is, if I run the same app within docker as a container, the same code is facing an error irrespective of http or https: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8081

While trying with http, I have set the environment variable: COSMOS_HTTP_CONNECTION_WITHOUT_TLS_ALLOWED as true and no luck.

**To Reproduce**
1. In docker compose, create a service for the emulator like below:

```
  
  cosmos:
    image: docker.repo1.uhc.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    command: [ "--protocol", "https", "--port", "8081" ]
    ports:
      - "8081:8081"
      - "1234:1234"
    environment:
      COSMOS_HTTP_CONNECTION_WITHOUT_TLS_ALLOWED: "true"

   some-spring-boot-app1:
    image: <docker-image-of-app>
    depends_on:
      cosmos:
        condition: service_started
    ports:
      - "8083:8082"
      - "5006:5005"
  
 some-app-2
  image: <docker-image-of-app>
  ports:
      - "8083:8082"
      - "5006:5005"

```
2. Configure a spring boot java app that has below cosmos sdk dependencies:
```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-cosmos</artifactId>
            <version>4.66.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
            <version>5.19.0</version>

        </dependency>
```

3. Create a CosmosClient like below from spring boot app code:

```
AzureKeyCredential credential = new AzureKeyCredential(<emulator-account-key>);
       
        return new CosmosClientBuilder()
                .endpoint(t"https://localhost:8081")
                .gatewayMode()
                .credential(credential);
```
4. Run the application using docker-compose
6. Error on startup is: 
`com.azure.cosmos.CosmosException: {"innerErrorMessage":"Connection refused: localhost/[0:0:0:0:0:0:0:1]:8081","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.66.1 Linux/6.10.14-linuxkit JRE/21.0.2 az-sd-cos/5.19.0" ...`

**Desktop (please complete the following information):**
 - macOS: [e.g. iOS] Sequoia 15.3 Apple M1 pro chip
 
- azure-cosmos sdk 4.66.1 and azure-spring-data-cosmos sdk 5.19.0
 - java
 
**Additional context**
As seen in docker compose, I have various services running on localhost under various ports which are able to connect to each other using localhost using different ports. So, this seems to be something between docker and emulator.

**Comment by alaye-ms** [comment]
Hello, I was able to get the same error as you, and a did a couple of things to remedy it. Firstly, I was able to get the localhost connection to work by adding `network_mode: host` to "some-spring-boot-app1." I'm not sure how your other applications are connecting via localhost without that, the default connection mode is bridge for my docker compose, which would necessitate using "https://cosmos:8081" as the endpoint, pulled from the service name.

Here is my full docker-compose file from my tests:

``` yaml
services:
  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    command: [ "--protocol", "https", "--port", "8081" ]
    ports:
      - "8081:8081"
      - "1234:1234"
    
  some-spring-boot-app1:
    image: local/some-spring-boot-app1
    depends_on:
      cosmos:
        condition: service_started
    ports:
      - "8080:8080"
    network_mode: host
```

Secondly, I needed to install the certs for the java sdk to use https mode, this is the dockerfile I used to accomplish that:

``` Dockerfile
FROM openjdk:17-jdk-alpine

WORKDIR $JAVA_HOME/lib/security/
COPY cosmos_emulator.cert /root/gateway.cert
RUN keytool -cacerts -importcert -alias cosmos_emulator -file ~/gateway.cert -noprompt -storepass changeit

WORKDIR /app
COPY target/some-spring-boot-app1-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
```

Specifically the 2nd-4th lines. I got that cert by running the commands in this guide:
https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-linux#get-certificate
under "Get Certificates"

Let me know if this helps!

**Comment by sramanan0425** [comment]
I already had the certs imported as per your suggestion in my Dockerfile. I added the network_mode and no luck. Finally, I was able to get it to work at least with http after adding an env variable GATEWAY_PUBLIC_ENDPOINT which I found embedded in a response to another issue in this repo. Wish they would add this to the emulator standard documentation

 ```
 cosmos:
    image: docker.repo1.uhc.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    hostname: cosmos.domain
    command: [ "--protocol", "http", "--port", "8082" ]
    ports:
      - "8082:8082"
      - "1234:1234"
    environment:
      COSMOS_HTTP_CONNECTION_WITHOUT_TLS_ALLOWED: "true"
      GATEWAY_PUBLIC_ENDPOINT: cosmos
```
