### ISSUE TITLE
VNext Data Explorer ignores Cosmos DB emulator port override

### ISSUE THREAD

**Issue by bitxon** [Azure/azure-cosmos-db-emulator-docker#168]
**Describe the bug**
Data Explorer is trying to fetch data from localhost:8081 even if docker image was launched with custom `--port 56001`

**To Reproduce**
1. Lunch docker image (with custom port for Cosmos endpoint)
    ```shell
    docker run --detach --name cosmosdb-vnext --publish 56001:56001 --publish 1234:1234 \
      mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview \
      --protocol https --port 56001
    ```
2. Open Data Explorer https://localhost:1234/
3. Data explorer is not able to connect to CosmosDbEmulator to see data
4. Open Chrome DevTools to see error 

**Expected behavior**
If docker image launched with custom port `--port 56001` -> Data Explorer respects it 

**Screenshots**

<img width="1023" alt="Image" src="https://github.com/user-attachments/assets/95ed5ae7-8246-447a-a350-226b5093ef38" />

<img width="1023" alt="Image" src="https://github.com/user-attachments/assets/0881ccef-a8bc-4c73-ac0f-0e2f1e8fd605" />

**Desktop (please complete the following information):**
 - OS: [Mac OS (M1)]
 - Browser Chrome

**Comment by andrew-mitt-docu** [comment]
Yes there is something wrong with the Ports for sure. We have port 8081 taken and need to change it. I would have expected us to be able to map 8079 to 8081 and then use 8079 in the client on the host machine, but this causes the client-side to time out.

```
services:
    cosmos-emulator:
        environment:
            # PORT: 8079 # Doesn't change anything, map 8079 to 8081 in the container
            AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 1
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
        ports:
            - 8079:8081
            - 10250-10255:10250-10255
```


```
CosmosClientOptions clientOptions = new()
{
    HttpClientFactory = () => new HttpClient(new HttpClientHandler()
    {
        ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
    }),
    ConnectionMode = ConnectionMode.Gateway,
};

using CosmosClient client = new(
    accountEndpoint: "https://localhost:8079/",
    authKeyOrResourceToken: "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
    clientOptions: clientOptions);

Database tspVariablesDb = await client.CreateDatabaseIfNotExistsAsync("mydb"); // Stalls
```

Everything else the same, changing 8079 to 8081 makes everything work again.
