### ISSUE TITLE
Container crashes on /scripts/utils.sh: line 183

### ISSUE THREAD

**Issue by jnsvd** [Azure/azure-cosmos-db-emulator-docker#171]
**Describe the bug**

The container crashes with the following output:

```
pg_ctl: directory "/data/db" is not a database cluster directory
Stopped all PG instances on /data/db
pg_ctl: directory "/home/cosmosdev/workernode*" does not exist
Stopped all PG instances on //home/cosmosdev/workernode*/
Deleting directory /data/db
/scripts/utils.sh: line 183:    26 Illegal instruction     (core dumped) openssl genpkey -algorithm RSA -out $WORKSPACE_ROOT/cosmosdev.key
Postgres failed to start
```

**To Reproduce**

Run `docker compose up -d` with:

```
services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-EN20250122
    container_name: cosmosdb
    ports:
      - "8081:8081"
      - "1234:1234"
    environment:
      EXPLORER_PROTOCOL: https
```

**Expected behavior**
Cosmos booting normally

**Desktop:**
 - OS: MacOS 15.3
 - Colima: v0.6.8 x86_64 architecture
 - Docker Engine - Community version: 27.3.1
 - Docker Server version: 24.0.9
