### ISSUE TITLE
Cosmos DB emulator does not create partitions and hangs on `Starting`

### ISSUE THREAD

**Issue by michasHL** [Azure/azure-cosmos-db-emulator-docker#181]
After pulling the latest docker image (mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest, sha256:c68e7ec98750b9a2dbb481f5be6467531b5df3a38058eec631639124eaa5e8d1) the emulator is hanging 
on `Starting` step in the logs without creating any partitions.

The explorer (https://localhost:8081/_explorer/index.html) is up but we can't create any containers. The certificate is also not available to download at this stage (https://localhost:8081/_explorer/emulator.pem).

I tried setting the `AZURE_COSMOS_EMULATOR_PARTITION_COUNT` environment variable to different values (1, 2, 5, 10, or completely removed) but this did not seems to be having an effect. After each try, I made sure to manually delete all the volumes.

**To Reproduce**
1. Startup docker with `docker compose up -d`
2. Check logs in Docker Desktop, or try to download SSL cert from https://localhost:8081/_explorer/emulator.pem

**Expected behavior**
The expected behavior would be to see all the partitions created and the normal output of started.
From this point on, the expectation would be to allow the creation of databases/containers as well as the download of the SSL cert.

**Screenshots**

![Image](https://github.com/user-attachments/assets/9ae51ff4-1ecf-4090-bd22-6dc25f355ac0)

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise, 24H2, 26100.3323
 - Browser Edge
 - Version 134.0.3124.51 (Official build) (64-bit)
 - Docker Desktop: 4.39.0 (184744): 

**Docker Images Used: **
 - Linux (mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest, sha256:c68e7ec98750b9a2dbb481f5be6467531b5df3a38058eec631639124eaa5e8d1)

**Arguments && Environment variables to start Docker:
 
**Docker Environment**
 - Docker compose (docker compose up -d)

```
name: local-development-emulators
services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmosdb
    volumes:
      - db-data:/tmp
    ports:
      - "8081:8081"
      - "10250-10255:10250-10255"
    restart: always
    environment:
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    networks:
      local-emulators:
        aliases:
          - cosmosdb
volumes:
  db-data:
networks:
  local-emulators:
```
 
**Additional context**
The `stable` image tag is out of evaluation period, so latest seems to be the only current one

**Comment by timmkrause** [comment]
Same here.

**Comment by michasHL** [comment]
So, I wiped my machine yesterday and set everything up again -- no luck.
What finally brought the emulator alive was enabling "Game Mode" using the Ryzen Master software. 
This of course disabled half my CCDs on my ThreadRipper 3990X. Not ideal but at least for me a workable solution.

Maybe still something worth investigating why the emulator seems to be having a hard time with lots of cores/threads.

**Comment by jcdickinson** [comment]
I also re-installed Windows completely this week, and I am still running into this. The repro is pretty simple:

1. Rancher desktop with moby
2. Per dotnet Aspire:
   ```sh
   docker run \
     --rm \
     -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true \
     -v tmp-vol:/tmp/cosmos/appdata \
     --name tmp-cosmos \
     mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
   ```
3. Do a very small amount of operations.
4. With _no_ in-flight requests against the container (i.e. quiesce the container): `docker stop tmp-cosmos`
5. Restart the container.

Outcome:

```
433c069a66dbd175b3cbec496f75dfbeeb20ae88488b68970cc7c7c505e935cf
This is an evaluation version.  There are [16] days left in the evaluation period.
2.14.21.0 (1c783d8f)
Copyright (C) Microsoft Corporation. All rights reserved.
Starting
Started 1/11 partitions
Started 2/11 partitions
Started 3/11 partitions
Started 4/11 partitions
Started 5/11 partitions
Started 6/11 partitions
Started 7/11 partitions
Started 8/11 partitions
```

And it hangs, which partition fails isn't consistent. I have poked around in the VM for logs but have found absolutely nothing (I checked `/var/log` and various places under `/tmp/cosmos/appdata`).

**Comment by Tow96** [comment]
Found same issue. However, I was able to make it work by commenting out the volume section:

```
services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmosdb
    # volumes:
    #   - ./data/cosmos:/tmp/cosmos
    ports:
      - "8081:8081"
      - "10250-10255:10250-10255"

    environment:
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
```
The output I get is this:

```
cosmosdb  | This is an evaluation version.  There are [10] days left in the evaluation period.
cosmosdb  | 2.14.21.0 (1c783d8f)
cosmosdb  | Copyright (C) Microsoft Corporation. All rights reserved.
cosmosdb  | Starting                                                                                                                                         
cosmosdb  | Started 1/2 partitions
cosmosdb  | Started 2/2 partitions
cosmosdb  | Started
```

My guess would be with how the container handles the partitions when mounted. Also, the amount of partitions seems to always be 1 higher than what is specified in the env variable. Is that normal?

**Comment by PhilG0lding** [comment]
I'm having the same issue myself. Seems to be working fine when only a few containers/items are created; I can stop and start the container as I like. As soon as I run some data seeding with a few thousands of items, I get the same issue as above when starting the container back up.

**Comment by tlaukkanen** [comment]
Getting the same in 2026 with the `latest` - hangs on `Started 10/11 partitions` and I only have few items in single container. 

Seems to work fine when I commented out the volume section as mentioned by @Tow96 👍

**Comment by lovettchris** [comment]
I had this problem and found deleting the volume helps:
```
docker compose down -v
```

**Comment by CampionFabio** [comment]
This issue remains...

I run a linux Mint with the below composer configuration

A fun fact is that it restarts fine along the day most times. 

My workaround is currently to remove the local `./cosmos-data`  every morning and let it restart fresh. luckily I do not require persistent data.


my `.env` has
```
COSMOS_EMULATOR_IP=127.0.0.1
```

```
  cosmos-emulator:
    container_name: cosmos-server
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    restart: unless-stopped
    tty: true
    mem_limit: 8g
    networks:
      default:
        ipv4_address: ${COSMOS_EMULATOR_IP}
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=100
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=${COSMOS_EMULATOR_IP}
      #- AZURE_COSMOS_EMULATOR_VERBOSE_LOGGING=true
    ports:
      - "8081:8081"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
      - "10256:10256"
      - "10350:10350"
      - "8900:8900"
      - "8901:8901"
      - "8902:8902"
    volumes:
      - ./cosmos-data:/tmp/cosmos/appdata
```
