### ISSUE TITLE
Linux vnext container w/ docker compose

### ISSUE THREAD

**Issue by famda** [Azure/azure-cosmos-db-emulator-docker#187]
Hi,

I'm trying to use the cosmos db linux container using docker compose without success. 
Here is my test scenario:
I have a dotnet web api and the vnext emulator, a network and the web api is connecting to cosmos db using EF core.

This simple scenario doesn't work. 
The web api can't connect with cosmos.

If I use aspire instead of compose, it works (probably because the web api access it via localhost with a proxy in between both).

Can you provide guidance on how to achieve this, please?

**Comment by WojciechNagorski** [comment]
I'm using cosmosdb in docker compose. I've tried vnext, and I've managed it to work, but currently, it does not work for other reasons.  

```
services:
  app-api:
    image: ${DOCKER_REGISTRY-}appapi
    build:
      context: .
      dockerfile: src/APP.Api/Dockerfile
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - app-storage
      - app-database
      - app-servicebus
    environment:
      CosmosDbSettings__UseEmulator: false
      ServiceBusSettings__TransportType: AmqpTcp
      ServiceBusSettings__ConnectionString: Endpoint=amqp://app-servicebus;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      CosmosDbSettings__ConnectionString: AccountEndpoint=https://app-database:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      StorageAccount__ConnectionString-Primary: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://app-storage:10000/devstoreaccount1;QueueEndpoint=http://app-storage:10001/devstoreaccount1;TableEndpoint=http://app-storage:10002/devstoreaccount1
      
  app-database:
    container_name: app-database
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    tty: true
    ports:
      - 8081:8081 # Data Explorer
    volumes:
      - vol_app_database:/tmp/cosmos
      - "./docker-compose.cosmosdb.cert.pfx:/mnt/host/default.sslcert.pfx"
    environment:
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
      AZURE_COSMOS_EMULATOR_CERTIFICATE: /mnt/host/default.sslcert.pfx
    networks:
      - app-network

	....

volumes:
  vol_app_storage:
    driver: local
  vol_app_database:
    driver: local

networks:
  app-network:
    driver: bridge 
```

You can find more information here https://github.com/testcontainers/testcontainers-dotnet/pull/1324/files about how to connect to vnext.
