### ISSUE TITLE
Have problem when try to start emulator i docker compose

### ISSUE THREAD

**Issue by L0ndra** [Azure/azure-cosmos-db-emulator-docker#27]
Use that configuration in docker compose 

```yml
cosmos:
    image: "microsoft/azure-cosmosdb-emulator"
    mem_limit: 2G
    ports:
      - "8081:8081"
      - "8900:8900"
      - "8901:8901"
      - "8979:8979"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
      - "10256:10256"
      - "10350:10350"
    networks:
      net:
        ipv4_address: 10.5.0.3
    volumes:
      - C:\Users\Illia_Lubenets\AppData\Local\CosmosDBEmulator\bind-mount:C:\CosmosDB.Emulator\bind-mount
```

and receive that error

```
cosmos_1   | Exception setting "BufferWidth": "The handle is invalid.
cosmos_1   | "
cosmos_1   | At C:\CosmosDB.Emulator\Start.ps1:37 char:1
cosmos_1   | + [Console]::BufferWidth = 32766
cosmos_1   | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cosmos_1   |     + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationExceptio 
cosmos_1   |    n
cosmos_1   |     + FullyQualifiedErrorId : ExceptionWhenSetting
cosmos_1   |  
cosmos_1   | Transcript started, output file is C:\CosmosDB.Emulator\bind-mount\Diagnostics\Transcript.log
```

**Comment by L0ndra** [comment]
I have solved this problem. 

All that I need it's to rebuild image instead of the image that uploaded to docker hub

**Comment by joshystuart** [comment]
@L0ndra what version of windows server did you use as the Dockerfile doesn't specify and Windows has dropped the `:latest` tag.

**Comment by maarten-kieft** [comment]
I ran in the same problem. I resolved it by adding tty:true to the docker-compose file. So the file will look like this:

```
cosmos:
    image: "microsoft/azure-cosmosdb-emulator"
    mem_limit: 2G
    tty:true
    ports:
      - "8081:8081"
      - "8900:8900"
      - "8901:8901"
      - "8979:8979"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
      - "10256:10256"
      - "10350:10350"
    networks:
      net:
        ipv4_address: 10.5.0.3
    volumes:
      - C:\Users\Illia_Lubenets\AppData\Local\CosmosDBEmulator\bind-mount:C:\CosmosDB.Emulator\bind-mount
```
