### ISSUE TITLE
Certificate thumbprint changes every time the container is re-started

### ISSUE THREAD

**Issue by tjrobinson** [Azure/azure-cosmos-db-emulator-docker#28]
I'm using this command to create the container:

```powershell
docker create --name azure-cosmosdb-emulator --memory 2GB --mount "type=bind,source=${env:LOCALAPPDATA}\azure-cosmosdb-emulator.hostd,destination=C:\CosmosDB.Emulator\bind-mount" --tty -p 8081:8081 -p 8900:8900 -p 8901:8901 -p 8979:8979 -p 10250:10250 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -p 10255:10255 -p 10256:10256 -p 10350:10350 microsoft/azure-cosmosdb-emulator
```

I then run:

```
pushd $env:LOCALAPPDATA\azure-cosmosdb-emulator.hostd
powershell .\importcert.ps1
```

Then stop and re-start the container (e.g. what happens if I shut my laptop down at the end of the day then start it up again the following day):

```
docker stop azure-cosmosdb-emulator
docker start azure-cosmosdb-emulator
```

When it restarts, it recreates the certificate (different thumprint), which I then have to re-import again. As an added complication, it's tricky to script/automate this as it doesn't generate this new certificate until the first request to the emulator.

This is an example of the `Transcript.log` after the restart:

```
**********************
Windows PowerShell transcript start
Start time: 20190423112804
Username: User Manager\ContainerAdministrator
RunAs User: User Manager\ContainerAdministrator
Machine: 713CE3FA5311 (Microsoft Windows NT 10.0.14393.0)
Host Application: powershell.exe -NoExit -NoLogo -Command C:\CosmosDB.Emulator\Start.ps1
Process ID: 1844
PSVersion: 5.1.14393.2636
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.2636
BuildVersion: 10.0.14393.2636
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\CosmosDB.Emulator\bind-mount\Diagnostics\Transcript.log

```

Until the first request is made, it pauses at this point.

```

    Directory: C:\CosmosDB.Emulator\bind-mount


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        4/23/2019  11:29 AM            513 CosmosDbEmulatorCert.cer

Key   : GremlinEndpoint
Value : {http://713ce3fa5311:8901/, http://192.168.127.20:8901/}
Name  : GremlinEndpoint


Key   : TableEndpoint
Value : {https://713ce3fa5311:8902/, https://192.168.127.20:8902/}
Name  : TableEndpoint


Key   : Key
Value : C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
Name  : Key


Key   : Version
Value : 2.2.1.0
Name  : Version


Key   : IPAddress
Value : 192.168.127.20
Name  : IPAddress


Key   : Emulator
Value : CosmosDB.Emulator
Name  : Emulator


Key   : CassandraEndpoint
Value : {tcp://713ce3fa5311:10350/, tcp://192.168.127.20:10350/}
Name  : CassandraEndpoint


Key   : MongoDBEndpoint
Value : {mongodb://713ce3fa5311:10255/, mongodb://192.168.127.20:10255/}
Name  : MongoDBEndpoint


Key   : Endpoint
Value : {https://713ce3fa5311:8081/, https://192.168.127.20:8081/}
Name  : Endpoint
```

**Comment by milismsft** [comment]
@tjrobinson the emulator must regenerate the certificates on every restart and that is because the certificate captures the current IP address of the container instance in the subject alternative name, which might change on a restart. I understand that might be an issue for repeat workload but with a bit of scripting you should be able to work around this limitation since the new certificate file is available in the mounted directory and automate your process so the certificates are imported after the emulator container was restarted.

**Comment by tjrobinson** [comment]
@milismsft Thanks for your help with this. I've run some tests and can see that the IP address is changing on each re-start of the container.

I will try to find some time to script the removal and replacement of the certificate when this occurs but there are a couple of complications:

* To avoid filling up my certificate store with old/invalid certificates, I'd like to remove these before importing the new/current one - though identifying them isn't straight-forward as there's no simple distinguisher, e.g. a `Friendly name`.
* As mentioned in my original post, the new certificate isn't generated until the first request to the emulator so there needs to be an automated request, followed by a wait/poll until a response is received,  before the new certificate can be imported.

The ideal scenario for me and I'm sure others, would be if some of this could be incorporated into the `importcert.ps1` script.

**Comment by milismsft** [comment]
@tjrobinson the certificate should be generated as soon as the emulator services are up and not when you make the first request to it.
I will look into your suggestion to add to the import script a friendly name. Meanwhile you can always use as an work around your own script that will import the certificate (start with the importcert.ps1) since the name/location are constant.

**Comment by tjrobinson** [comment]
@milismsft I tried taking a different approach to this, and have configured the container to use a fixed IP address, using docker compose:

```yaml
version: '2.4' # Do not upgrade to 3.x yet, unless you plan to use swarm/docker stack: https://github.com/docker/compose/issues/4513

networks:
  default:
    external: false
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

services:

  # Image: https://hub.docker.com/r/microsoft/azure-cosmosdb-emulator/
  # After starting up, run %LOCALAPPDATA%\Local\azure-cosmosdb-emulator.hostd\importcert.ps1 as Administrator
  cosmosdb:
    container_name: "cosmosdb"
    image: 'microsoft/azure-cosmosdb-emulator:latest'
    platform: windows
    tty: true
    mem_limit: 2GB
    ports:
        - '8081:8081'
        - '8900:8900'
        - '8901:8901'
        - '8979:8979'
        - '10250:10250'
        - '10251:10251'
        - '10252:10252'
        - '10253:10253'
        - '10254:10254'
        - '10255:10255'
        - '10256:10256'
        - '10350:10350'
    networks:
      default:
        ipv4_address: 172.16.238.246
    volumes:
        - '${LOCALAPPDATA}\azure-cosmosdb-emulator.hostd:C:\CosmosDB.Emulator\bind-mount'
```

This works well, but unfortunately the Container ID is also included in the list of Subject Alternative Names in the certificate. This can't be configured to be the same, and unfortunately means the certificate changes on each restart.

Can the Container ID be removed from the Subject Alternative Names?

```
Subject Alternative Name
        DNS Name=d38484286e81
        DNS Name=localhost
        IP Address=172.16.238.246
        IP Address=127.0.0.1
        DNS Name=172.16.238.246
        DNS Name=127.0.0.1
```

**Comment by tjrobinson** [comment]
Aha, solved the Container ID problem by adding `hostname: "cosmosdb"` to the docker compose file:

```
# Image: https://hub.docker.com/r/microsoft/azure-cosmosdb-emulator/
  # After starting up, run %LOCALAPPDATA%\Local\azure-cosmosdb-emulator.hostd\importcert.ps1 as Administrator
  cosmosdb:
    container_name: "cosmosdb"
    hostname: "cosmosdb"
    image: 'microsoft/azure-cosmosdb-emulator:latest'
    platform: windows
    tty: true
    mem_limit: 2GB
    ports:
        - '8081:8081'
        - '8900:8900'
        - '8901:8901'
        - '8979:8979'
        - '10250:10250'
        - '10251:10251'
        - '10252:10252'
        - '10253:10253'
        - '10254:10254'
        - '10255:10255'
        - '10256:10256'
        - '10350:10350'
    networks:
      default:
        ipv4_address: 172.16.238.246
    volumes:
        - '${LOCALAPPDATA}\azure-cosmosdb-emulator.hostd:C:\CosmosDB.Emulator\bind-mount'
```

This means that `cosmosdb` is included in the Subject Alternative Names instead of the Container ID.

So far so good...
