### ISSUE TITLE
Unable to connect to cosmos db emulator when using linux containers with container network

### ISSUE THREAD

**Issue by ajaygoyal** [Azure/azure-cosmos-db-emulator-docker#76]
I have a .net 6 app that needs to connect to cosmos db emulator.

I have below setup:

test-app:
   env_file:
     - ../../Environment/local.env
   build:
     context: ./
     dockerfile: Services/Dockerfile
   ports:
     - "80:80" 
   entrypoint: >
     /bin/sh -c "
       update-ca-certificates
       dotnet MyApp.dll"
   depends_on:
     - cosmosdb_emulator
   networks:
     - container_network

 cosmosdb_emulator:
   image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
   ports:
     - "8081:8081"
   environment:
     AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
     ACCEPT_EULA: "Y"
   networks:
     - container_network

Downloaded the cert on host using:
curl -k https://host.docker.internal:8081/_explorer/emulator.pem > /c/certs/emulatorcert.crt

But application fails to connect to the cosmos with below error:

2023-10-22 20:06:51  ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2023-10-22 20:06:51  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch

Disabling SSL is not something that we want to do.

**Comment by kbegiedza** [comment]
Did you install downloaded cert inside your `test-app` container?

**Comment by abkolant-MSFT** [comment]
Could you check the [YAML file](https://github.com/Azure/cosmosdb-emulator-recipes/blob/main/dotnet/linux/docker-compose.yml) in the .NET example in this repo, https://github.com/Azure/cosmosdb-emulator-recipes. This [README](https://github.com/Azure/cosmosdb-emulator-recipes/blob/main/dotnet/linux/README.md) has more details.

**Comment by JoeAmedeo** [comment]
Is there a way to make this work without using `HttpClientHandler.DangerousAcceptAnyServerCertificateValidator` as a cert validation callback? I am trying to set up effectively the same application as the example, but with the [Azure Cosmos DB Migration Tool](https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-migrate-desktop-tool?tabs=azure-cli) where I can't make this configuration, and removing that from the example app causes the same RemoteCertificateNameMismatch error.

I am not super confident on my understanding of SSL certificates, but is it possible to use the /GenCert={host name for the service} arg to make this work? I have been following [this example from another issue](https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/55) and tried overriding the `./startup.sh` file to use said argument, but at that point the emulator will not start.

**Comment by Davilink** [comment]
This really seem like a oversight. I can't use cosmos emulator in devcontainer because of this simple issue... one think could be to add the hostname as an altername name in the certificate.

**Comment by Davilink** [comment]
Ok, i finally did it.

I inspected the certificate and found out that it's use an alternate name but suffix with the ".DOMAIN" after the hostname, so here what i did:

```yaml
  cosmos:
    image:  mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    hostname: cosmos # Required otherwise the the hostname will be a random string
    restart: unless-stopped
    ports:
      - 8081:8081 # Required to allow the docker build step to retrieve the certificate add build time (and if you want to access the include data explorer from the host machine)
    networks:
      game:
        aliases:
          - "cosmos.DOMAIN" # Required
```

When my devcontainer is build i call a script to install the certificate at the correct location for me.
Note: in the documentation (https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator?tabs=docker-linux%2Ccsharp&pivots=api-nosql#export-the-emulators-tlsssl-certificate) is say to put the certificate at `/usr/local/share/ca-certificates`, but update-ca-certificates look into `/usr/share/ca-certificates` (notice the lack of `local`).

```bash
echo "Installing cosmos db emulator ssl certificate"

mkdir /usr/share/ca-certificates/cosmos

curl -k https://host.docker.internal:8081/_explorer/emulator.pem > /usr/share/ca-certificates/cosmos/emulator.crt

chmod o+r /usr/share/ca-certificates/cosmos/emulator.crt
echo "cosmos/emulator.crt" >> /etc/ca-certificates.conf
update-ca-certificates
```

and in appsettings.development.json
```jsonc
{
// ...
"ConnectionStrings": {
  "CosmosConnection": "AccountEndpoint=https://cosmos.DOMAIN:8081/;AccountKey=C2y6yDjf**************"
}
// ...
```

**Comment by Davilink** [comment]
I got it working without using the `HttpClientHandler.DangerousAcceptAnyServerCertificateValidator`.

I inspected the certificate and found out that it does contains alternate subject name, but there a twist, you have to declare a hostname for your service.

`docker-compose.yml (good)`
```yaml
version: '3'
services:
  cosmos:
    image:  mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    hostname: cosmos # <-- required
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      game:
        aliases:
          - "cosmos.DOMAIN" # <-- required
```

![image](https://github.com/Azure/azure-cosmos-db-emulator-docker/assets/1498932/6f91c4b9-d61a-420f-94b3-be7dc1028c56)

If you don't specifiy a hostname, docker will generate a random one
example:

`docker-compose.yml (bad)`
```yaml
version: '3'
services:
  cosmos:
    image:  mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    # hostname: cosmos
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      game:
        aliases:
          - "cosmos.DOMAIN" # <-- required
```
![image](https://github.com/Azure/azure-cosmos-db-emulator-docker/assets/1498932/c77113c3-77e6-4bc3-b4e9-ae6235c2569e)

Note: I tried using the `cosmosdbemulatormtls.localhost` but it doesn't work (problably because of the `.localhost` at the end). 

The hostname doesn't have to be `cosmos`, i just choose that name, but if you change it don't forget to update the aliase use in the docker compose file.

`docker-compose.yml (alternate config good)`
```yaml
version: '3'
services:
  cosmos:
    image:  mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    hostname: othername
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      game:
        aliases:
          - "othername.DOMAIN"
```

Once the cosmos emulator container is started, it take a minute or so to be able to retrieve the certificate.
I'm currently setting up a devcontainer using cosmos emulator and added this in my `postCreateCommand.sh` script:

```bash
#!/bin/bash
echo "Installing cosmos db emulator ssl certificate"

mkdir /usr/share/ca-certificates/cosmos

for i in {1..60};
do
  curl -fsk https://cosmos.DOMAIN:8081/_explorer/emulator.pem > /usr/share/ca-certificates/cosmos/emulator.crt
  if [ $? -eq 0 ];  then
    echo "Cosmos emulator ready"
    break
  else
    echo "Not ready yet..."
    sleep 10
  fi
done

chmod o+r /usr/share/ca-certificates/cosmos/emulator.crt
echo "cosmos/emulator.crt" >> /etc/ca-certificates.conf
update-ca-certificates
```
after this, you will need to use the `cosmos.DOMAIN:8081` (update the port number if your setup use an another port)

`appsetings.Development.json`
```jsonc
{
  // ...
  "ConnectionStrings": {
    "CosmosConnection": "AccountEndpoint=https://cosmos.DOMAIN:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
  },
  // ...
}
```
The account key is the default one used by the cosmos emulator, so you can copy-paste the connection string for you use.

**Comment by cdytoby** [comment]
Additional information to the post above:

curl is default not installed. So for automation, you need to install curl.

This is the example snippet to the `Dockerfile` of the asp.net project

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
RUN apt-get update && apt-get install -y curl
EXPOSE 8080
```

Credit: https://stackoverflow.com/questions/73678713/how-to-install-curl-from-dockerfile

**Comment by hughesjs** [comment]
I'm getting the same as @cdytoby... Any ideas beyond just disabling SSL validation for now?

**Comment by hughesjs** [comment]
Okay, so I worked out my problem.

The `cosmos.domain` listed as an alias above isn't just "any generic domain" it's literally ".domain".

Seems to me you can summarise that long post into:

- Set the `hostname` in your compose (not/as well as the `container_name`).
- Add an alias to the network for `<hostname>.domain`

This will then ensure that you can resolve the emulator with a hostname that is present in the certificate's alternate names

You can probably get all of this from the long answer above, but I missed it so figured I'd share what I learned a bit more concisely.

**Comment by hughesjs** [comment]
So following on from my last post, I can go one better. 

I don't think you even need the alias, just set the hostname to `cosmos.domain`

**Comment by hughesjs** [comment]
That's great to hear, thanks! Let me know if there's anything I can do to help

**Comment by seesharprun** [comment]
I'm working on a pull request for an existing code sample repository and am trying to implement these: https://github.com/Azure-Samples/cosmos-db-nosql-query-samples/pull/35

Once it's ready, I will follow up on this thread

**Comment by seesharprun** [comment]
Quick update. I had a breakthrough. Here's the updated YML files that will be included in the new documenation:

## GitHub Action workflow

```yml
on:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
        ports:
          - 8081:8081
          - 10250-10255:10250-10255
        env:
          AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 5
          AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Install SSL certificate
        run: |
          retry_count=0
          max_retry_count=10
          until sudo curl --insecure --silent --fail --show-error "https://localhost:8081/_explorer/emulator.pem" --output "/usr/local/share/ca-certificates/cosmos-db-emulator.crt"; do
            if [ $retry_count -eq $max_retry_count ]; then
              echo "Failed to download certificate after $retry_count attempts."
              exit 1
            fi
            echo "Failed to download certificate. Retrying in 5 seconds..."
            sleep 5
            retry_count=$((retry_count+1))
          done
          sudo update-ca-certificates
      - name: Run .NET test
        run: dotnet test --logger "console" --logger "trx;verbosity=detailed"
        env:
          COSMOSDB__CONNECTIONSTRING: "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
        working-directory: ./validate/test
      - name: Upload TRX test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: validate/test/TestResults/**/*.trx
```

#### Devcontainer `postCreateCommand` shell script

```bash
#!/bin/bash

echo "Installing Azure Cosmos DB emulator certificate"

for _ in {1..10};
do  
  if curl --insecure --silent --fail --show-error https://cosmosdb.domain:8081/_explorer/emulator.pem > /usr/local/share/ca-certificates/cosmos-db-emulator.crt;
  then
    echo "Azure Cosmos DB emulator certificate downloaded..."
    break
  else
    echo "Failed to download Azure Cosmos DB emulator certificate. Retrying in 5 seconds..."
    sleep 5
  fi
done

update-ca-certificates
```

I'll post another update on this thread once the new documentation is live. Thanks for your patience!

**Comment by hughesjs** [comment]
Is there a reason the cert has to be regenerated on every container start? Being able to just bake the cert into our containers at build time would make this whole process a lot more straightforward

**Comment by seesharprun** [comment]
I don't know the answer to that question. It's been my experience that the certificate can be different between starts of the container.

@sajeetharan, do you know more about how the certificates work in the Docker (Linux) container image?

**Comment by seesharprun** [comment]
I also am wondering aloud if there's a healthcheck built into the container image. 

GitHub cites Redis and PostgreSQL container images as examples of container images with good health checks you can use to make sure the container is ready. Here's some examples in service containers within GitHub Actions (using `docker run --health-cmd`):

---

Redis has the `redis-cli` tool and you can run the `ping` command to see if its ready.

```yml
jobs:
  run-redis:
    services:
      rediscache:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```

<https://docs.github.com/actions/using-containerized-services/creating-redis-service-containers>

---

PostgreSQL has the `pg_isready` tool.

```yml
jobs:
  run-postgres:
    services:
      postgresdb:
        image: postgres
        env:
          POSTGRES_PASSWORD: "P@ssw.rd"
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```

<https://docs.github.com/actions/using-containerized-services/creating-postgresql-service-containers>

---

You can even do it with MongoDB.

```yml
on:
  workflow_dispatch
jobs:
  run-mongodb:
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: "mongo"
          MONGO_INITDB_ROOT_PASSWORD: "P@ssw.rd"
        options: >-
          --health-cmd "mongosh --username mongodb --password P@ssw.rd --eval 'db.runCommand("ping").ok' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
```

If a healthcheck script or tool doesn't already exist, it may be worth building. In the interim we can probably build custom Docker container images and write our own health check script.
