### ISSUE TITLE
Linux docker container runs but function app CosmosDBTrigger does nothing. Windows msi does work.

### ISSUE THREAD

**Issue by Barsonax** [Azure/azure-cosmos-db-emulator-docker#82]
**Describe the bug**
Linux docker container runs but function app CosmosDBTrigger does nothing. Windows msi does work.

**To Reproduce**

1. Start the cosmosdb container using this docker compose file
```
services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: "cosmosdb"
    ports:
      - "8081:8081"
      - "8900:8900"
      - "8901:8901"
      - "8979:8979"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
      - "10256:10256"
      - "10350:10350"
```

2. Ensure https certificate is trusted

3. Run a azure function locally that uses CosmosDBTrigger. Notice how nothing happens, no errors are logged either. Leases are not created even if CreateLeaseContainerIfNotExists is set to true.

**Expected behavior**
Atleast an error describing what went wrong or even better just make it work like the windows msi emulator.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - VersionlLatest

**Docker Images Used: **
 - Linux

**Arguments && Environment variables to start Docker:
 
**Docker Environment**
 - Docker compose
 
**Additional context**

**Comment by Barsonax** [comment]
I managed to get it to work with this docker compose definition:
```
services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: "cosmosdb"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    ports:
      - 8081:8081
```

Hope this will help anyone who stumbles on this but the real fix is to update the docs.

AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE is apparently needed when running in a docker container. Probably because its in a different subnet. Was quite hard to find though that this is the fix.
