### ISSUE TITLE
AZURE_COSMOS_EMULATOR_PARTITION_COUNT is ignored

### ISSUE THREAD

**Issue by hades200082** [Azure/azure-cosmos-db-emulator-docker#83]
**Describe the bug**
When starting the container, it seems to "sort of" ignore the `AZURE_COSMOS_EMULATOR_PARTITION_COUNT` environment variable and always tries to start 11 partitions.

I set `AZURE_COSMOS_EMULATOR_PARTITION_COUNT=4` and this was the log output in docker:

![image](https://github.com/Azure/azure-cosmos-db-emulator-docker/assets/1023581/442e7238-6dce-404e-b52d-b54764b6811b)

My compose file:

```yml
version: "3.9"
volumes:
  cosmos-db-volume:

networks:
  customnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

services:
  cosmosdb:
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=4
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.1.1
    ports:
      - "8081:8081"
      - "8900:8900"
      - "8901:8901"
      - "8979:8979"
      - "10250-10256:10250-10256"
      - "10350:10350"
    networks:
      customnet:
        ipv4_address: 192.168.55.20
    volumes:
      - cosmos-db-volume:/tmp/cosmos/appdata
```

**Expected behavior**
It should only start the number of partitions specified.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Docker Images Used: **
 - Linux <--

**Arguments && Environment variables to start Docker:
 
**Docker Environment**
 - Docker compose
 
**Additional context**
