### ISSUE TITLE
Container hangs on...

### ISSUE THREAD

**Issue by pvpmartins** [Azure/azure-cosmos-db-emulator-docker#93]
**Describe the bug**
Often times the Linux emulator docker container completely freezes. No matter what I do, it keeps like that for a while. It is really time consuming.

 - Linux (mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest)

 
**Docker Environment**
```
version: '3'
services:
  cosmosdb:
    image: 'mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest'
    environment:
      SA_PASSWORD: 'Your_password123'
    cap_add:
      - SYS_PTRACE
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8000M # Increase memory limit to 4GB (4000 megabytes)
        reservations:
          cpus: '1'
          memory: 4000M # Increase memory reservation to 2GB (2000 megabytes)

```
