### ISSUE TITLE
Docker Image (Linux) Disable Rate Limiting

### ISSUE THREAD

**Issue by JamesBrightley** [Azure/azure-cosmos-db-emulator-docker#97]
The Windows emulator allows you to disable rate limiting via the system tray. How can this be disabled when running the emulator docker image? The start.sh appears to allow additional start up arguments from the environment variable `AZURE_COSMOS_EMULATOR_ARGS` but this does not appear to be respected as I quickly start to get 429 responses when trying to insert a lot of data.

docker-compose yaml snippet:

  cosmosdb:
    container_name: cosmosdb
    hostname: cosmosdb
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    platform: linux
    tty: true
    restart: always
    mem_reservation: 8gb
    cpu_percent: 50
    environment:
      - AZURE_COSMOS_EMULATOR_DEFAULT_PARTITION_COUNT=30
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=30
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
      - AZURE_COSMOS_EMULATOR_ARGS=/DisableRateLimiting
    ports:
       - "8081:8081"
       - "10250-10255:10250-10255"
    volumes:
      - cosmos:/tmp/cosmos/appdata

I would expect there to be no rate limiting

OS: Windows 11

**Docker Images Used: **
 - Linux

**Comment by jalbiero** [comment]
@JamesBrightley AFAIK in my case `AZURE_COSMOS_EMULATOR_ARGS` is working Ok, but I am enclosing the arguments in single quotation marks. My compose.yaml file looks like this:

```yaml
services:
  MyFooService:
    # This is a 'wrapper' image that try to solve the lack of 'curl' commmand in the
    # oficial CosmosDb image. 
    # See the reported bug: https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/103
    image: foo/cosmosdb
    build:
      dockerfile_inline: |
        FROM mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
        RUN apt-get update && \
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
            curl
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=1
      - AZURE_COSMOS_EMULATOR_ARGS='/DisableRateLimiting /EnablePreview' 
    ports:
      - 8081:8081
      - 10250-10255:10250-10255
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8081/_explorer/emulator.pem"]
      interval: 10s
      retries: 15
      timeout: 3s
    volumes:
      - FooVol:/tmp/cosmos/appdata
volumes:
  FooVol:
```

Without `/DisableRateLimiting` my unit tests fail randomly all the time.
